"""
BURSTTEMPORALGAT Temporal Graph Attention Network for Burst-Based Neuron Importance Modeling

    This module defines the BurstTemporalGAT model, a neural architecture designed
    to model temporal bursting dynamics in large-scale spiking neural networks.

    The model operates on a sequence of graph-structured time windows corresponding
    to a single burst. For each window:
      1. A Graph Attention Network (WindowGAT) computes vertex embeddings using
         neuron-level features and synaptic connectivity.
      2. The sequence of window-level vertex embeddings is stacked across time.
      3. A Gated Recurrent Unit (GRU) integrates temporal information across windows.
      4. A linear output layer produces a scalar importance value for each neuron,
         representing its predicted influence on future bursting behavior.

    This model is intended to be used with binned spike data and static or
    quasi-static connectivity graphs generated by Graphitti simulations.

Syntax:
    model = BurstTemporalGAT(
                vertex_in=<int>,
                edge_in=<int>,
                hid=<int>,
                heads=<int>,
                gru_hid=<int>
            )

Input:
    x_seq            - Tensor of shape [T, N, F], where:
                         T = number of temporal windows in a burst
                         N = number of neurons
                         F = number of vertex features
    edge_index_seq   - List (length T) of edge index tensors [2, E]
    edge_attr_seq    - List (length T) of edge attribute tensors [E, edge_in]

Output:
    - Tensor of shape [N, 1] containing predicted neuron importance values for
      the final time window of the burst.

Author: Marina Rosenwald

Last updated: 12/16/2025 
"""


from windowGAT import WindowGAT
import torch.nn as nn
import torch

class BurstTemporalGAT(nn.Module):
    def __init__(self, vertex_in, edge_in, hid=64, heads=4, gru_hid=128):
        super().__init__()
        self.gat = WindowGAT(vertex_in, edge_in, hid, heads)
        self.gru = nn.GRU(input_size=hid*heads, hidden_size=gru_hid, batch_first=True)
        self.out = nn.Linear(gru_hid, 1)

    def forward(self, x_seq, edge_index_seq, edge_attr_seq):
        T, N, F = x_seq.shape
        vertex_embeds = []
        for t in range(T):
            x_t = x_seq[t]
            edge_index_t = edge_index_seq[t]
            edge_attr_t = edge_attr_seq[t]
            h_vertexs = self.gat(x_t, edge_index_t, edge_attr_t) 
            vertex_embeds.append(h_vertexs)
        H = torch.stack(vertex_embeds, dim=1)
        out_seq, _ = self.gru(H)  
        return self.out(out_seq[:, -1])